name: ihartdan
favicon: null
layout_spectrum: 0.99361
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414549'
    - '#e1482f'
    - '#e6e6e6'
    - '#e6c646'
    - '#5bcc8b'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.32700612070038915
purpose: []
