name: ihartdan
favicon: null
layout_spectrum: 0.74708
typography_spectrum: 0.75543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#323232'
    - '#979797'
    - '#666666'
    - '#71eed0'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
