name: ihartdan
favicon: null
layout_spectrum: 0.48164
typography_spectrum: 0.4783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#ecdbee'
    - '#fa3450'
    - '#7d0e17'
    - '#604c34'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
