name: ihartdan
favicon: null
layout_spectrum: 0.98338
typography_spectrum: 0.52046
title: 'Majestity '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d9dd'
    - '#555656'
    - '#df4227'
    - '#8c8f91'
    - '#ed9787'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
