name: ihartdan
favicon: null
layout_spectrum: 0.99361
typography_spectrum: 0.73785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fedb10'
    - '#c6ad12'
    - '#1a1b15'
    - '#4e4616'
    - '#8a837c'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.32700612070038915
purpose: []
