name: ihartdan
favicon: null
layout_spectrum: 0.99917
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#4d4e50'
    - '#b9bfbd'
    - '#85929a'
    - '#262a2b'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
